#pragma once

// Generated by CMake from the version in the root CMakeLists.txt.
#define API_FUNCTIONS_VERSION_MAJOR 0
#define API_FUNCTIONS_VERSION_MINOR 1
#define API_FUNCTIONS_VERSION_PATCH 0
#define API_FUNCTIONS_VERSION_STRING "0.1.0"
